### ISSUE TITLE
是不是只支持实体类的单向转换?

### ISSUE THREAD

**Issue by xianzheTM** [04637/delombok#1]
RT.
1.只能将我写的lombok的实体类转为没有lombok的实体类吗?可不可以反过来?
2.支持哪些lombok注解?

**Comment by jiguantong** [comment]
> RT.
> 1.只能将我写的lombok的实体类转为没有lombok的实体类吗?可不可以反过来?
> 2.支持哪些lombok注解?

1. 所有lombok的注解都支持
2. 只可以单向转换, 将lombok的注解转换为完整代码, 不支持反向转注解
