### ISSUE TITLE
你好 请问一下有没有兴趣 在打源码包的时候生成delombok 的制作方向

### ISSUE THREAD

**Issue by Seriels** [04637/delombok#2]
因为调试 的时候总会奇奇怪怪的

**Comment by jiguantong** [comment]
> 因为调试 的时候总会奇奇怪怪的

打源码包是什么意思呀?
插件在build菜单中提供了对整个项目的delombok哦  可以试试满足不满足

**Comment by Seriels** [comment]
> > 因为调试 的时候总会奇奇怪怪的
> 
> 打源码包是什么意思呀?
> 插件在build菜单中提供了对整个项目的delombok哦 可以试试满足不满足

换个意思就是说 在使用 maven 插件  <artifactId>maven-source-plugin</artifactId> 时 类似 打包出来的源码 包是 delombok的

**Comment by jiguantong** [comment]
> > > 因为调试 的时候总会奇奇怪怪的
> > 
> > 
> > 打源码包是什么意思呀?
> > 插件在build菜单中提供了对整个项目的delombok哦 可以试试满足不满足
> 
> 换个意思就是说 在使用 maven 插件 maven-source-plugin 时 类似 打包出来的源码 包是 delombok的

有时间的话会考虑开发哦

**Comment by jiguantong** [comment]
Hello 已经有人开发了该插件  尝试下是否满足  https://github.com/awhitford/lombok.maven

**Comment by Seriels** [comment]
非常感谢推荐
