### ISSUE TITLE
不管用

### ISSUE THREAD

**Issue by zhengxudong** [04637/delombok#3]
build-->delombok project以后没有任何效果

**Comment by jiguantong** [comment]
> build-->delombok project以后没有任何效果

您好  由于文件被重写， 你打开的文件有缓存， 所以看到的还是老的代码，关闭文件重新打开试试， 如果还没有效果的话， 看下右下角是否有报错信息  反馈给我

**Comment by jiguantong** [comment]
v1.18.4 已加速重载文件， delombok后你将可以立即看到完整代码
