### ISSUE TITLE
不知道为什么不起作用

### ISSUE THREAD

**Issue by mzzsfy** [04637/delombok#4]
在commit时有这个弹窗
![image](https://user-images.githubusercontent.com/43053461/91825182-7d3e1600-ec6e-11ea-80d4-082b236aaf1b.png)
在
![image](https://user-images.githubusercontent.com/43053461/91825239-8f1fb900-ec6e-11ea-8c09-7fefe8110b9d.png)
没任何反应

环境:idea2020.2

**Comment by jiguantong** [comment]
> 在commit时有这个弹窗
> ![image](https://user-images.githubusercontent.com/43053461/91825182-7d3e1600-ec6e-11ea-80d4-082b236aaf1b.png)
> 在
> ![image](https://user-images.githubusercontent.com/43053461/91825239-8f1fb900-ec6e-11ea-8c09-7fefe8110b9d.png)
> 没任何反应
> 
> 环境:idea2020.2

你好，不好意思刚看到这个问题。
在弹出该弹窗时，IDEA有下角应该有个红色感叹号，将其中的报错信息反馈给我我排查下。

**Comment by mzzsfy** [comment]
![image](https://user-images.githubusercontent.com/43053461/92690198-27a2f100-f373-11ea-9fbe-bb527f323e66.png)
并没有气泡

**Comment by jiguantong** [comment]
[delombok.zip](https://github.com/04637/delombok/files/5199649/delombok.zip)
请尝试离线安装该版本，看是否有具体的报错信息供我排查问题

**Comment by mzzsfy** [comment]
在commit时:

Delombok: Overwriting src failed! Source 'C:\Users\user\Desktop\[REDACTED]\src' does not exist[org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1383), org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1346), org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1246), org.apache.commons.io.FileUtils.copyDirectoryToDirectory(FileUtils.java:1187), dev.aid.delombok.utils.RushUtils.rush(RushUtils.java:87), dev.aid.delombok.checkin.DlCheckinHandler$1.run(DlCheckinHandler.java:68), com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935), com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490), com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79), com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235), com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170), com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629), com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581), com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60), com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157), com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235), java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668), java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665), java.base/java.security.AccessController.doPrivileged(Native Method), java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665), java.base/java.lang.Thread.run(Thread.java:834)]

**Comment by mzzsfy** [comment]
点击
![image](https://user-images.githubusercontent.com/43053461/92691754-a7ca5600-f375-11ea-9c20-89080d2f1959.png)
还是没有任何效果

**Comment by jiguantong** [comment]
报错提示src路径不存在，可能是因为项目目录结构的问题，可否将你的项目打包发我我测试修复下？如果不方便的话，可以建一个测试项目，可以重现该问题即可，将该测试项目发我下

**Comment by mzzsfy** [comment]
[test.zip](https://github.com/04637/delombok/files/5199770/test.zip)
这个可以复现

**Comment by jiguantong** [comment]
已找到问题，当前还不支持在顶级项目中对子项目delombok，我试了下直接打开子项目开发时delombok是没有问题的，比如你发的test项目中有a项目，直接用idea打开a项目进行开发，使用delombok是没有问题的哦，后续有时间我会考虑支持该场景

**Comment by mzzsfy** [comment]
好的,希望早日支持
