### ISSUE TITLE
About the use of Delombok plugin.

### ISSUE THREAD

**Issue by ChinaJeckXu** [04637/delombok#6]
In IDEA 2020.3 and above, using the latest version of the Delombok plug-in cannot perform the Delete Lombok plug-in effect on the Maven aggregation project.

**Comment by ChinaJeckXu** [comment]
🌟 This may be a new feature support.

**Comment by jiguantong** [comment]
已支持, 请尝试新版  v-1.18.4.2

**Comment by ChinaJeckXu** [comment]
@04637 目前在IDEA 2020.3使用delombok v-1.18.4.2版本的情况下，依然没有完全的支持包含子模块的Delete Lombok 插件效果，目前看到的直接效果是：
情况1、在Maven 子模块数量较少的情况下（2个子模块，且独立运行（添加了程序启动器））可以实现Delete Lombok 插件效果。
情况2、在Maven子模块数量较多的情况下（61个子模块，且全部不能独立运行，属于封装的自动配置 starter模块 ）无法实现Delete Lombok 插件效果（只能将部分类的源代码反编译，且文件名固定）。这个问题或许不好定位，在时间允许的情况下，可以进一步沟通，定位问题。

**Comment by jiguantong** [comment]
加我微信   _04637
| |
04637
|
|
***@***.***
|
签名由网易邮箱大师定制
On 7/15/2021 ***@***.***> wrote：

@04637 目前在IDEA 2020.3使用delombok v-1.18.4.2版本的情况下，依然没有完全的支持包含子模块的Delete Lombok 插件效果，目前看到的直接效果是在Maven 子模块数量较少的情况下（2个子模块，且独立运行（添加了程序启动器））可以实现Delete Lombok 插件效果，在Maven子模块数量较多的情况下（61个子模块，且全部不能独立运行，属于封装的自动配置 starter模块 ）无法实现Delete Lombok 插件效果。这个问题或许不好定位，在时间允许的情况下，可以进一步沟通，定位问题。
